### ISSUE TITLE
Vector3 has no controls

### ISSUE THREAD

**Issue by lukasIO** [rabbitControl/rcp-ts-client#1]
I can see the name but no controls for it

**Comment by i-n-g-o** [comment]
hi.
thanks for trying it out and reporting this issue.
not all types are implemented yet, all the vectors are missing.

if you use a Vector3F32, then you should see the string "vector"?

**Comment by lukasIO** [comment]
yes. that's exactly what I'm seeing. 
I implemented the protocol for Unity3d and the support for Vectors would come in extremely handy. 
Is it something that you have on your soon-to-do or are you looking for a community based effort? 
to have a web-client that supports all types would help a lot to promote RCP as a easy to use and fast to setup protocol...

**Comment by i-n-g-o** [comment]
oh nice, great!
do you want to host the unity3d implementation in the rabbitControl-project space?
(would be great!)

i think i can have a look at the vector-ui in the next couple of days. should not be too hard to implement.

**Comment by lukasIO** [comment]
it's far from polished and relies on Unity Reactive Extensions for a two-way binding of the values. (https://github.com/neuecc/UniRx).
If you want you can check it out here https://github.com/lukasIO/UniRCP.
For me it would not be a problem to move it to the rabbitControl project space. Just wanted to make clear that it's server only and not complete :)

**Comment by i-n-g-o** [comment]
a lot of parts in rabbitControl are work in progress ;)
i sent you an invitation... you should be able to create a new repository in the rabbitControl space.

**Comment by joreg** [comment]
@lukasIO great to see your work on this! regarding [your fork of rcp-sharp](https://github.com/lukasIO/rcp-csharp-Unity3d) to adapt it for unity types: have you thought of creating simple extension methods to convert types, rather than modifying the project? that would keep it much more easy to maintain on your end in the long run. 

are you in our [chat](https://riot.im/app/#/room/#rcp:matrix.org)? would probably best to talk about this there if you have any question..

**Comment by lukasIO** [comment]
@i-n-g-o thanks, will do it over the weekend!

@joreg I thought about that briefly, but didn't have a clever idea how to deal with the using statements in that case, so replacing seemed easier. The annoying part is that afaik System.Drawing.dll and System.Numerics.dll would have to be added as external files to the project in this case, eventhough there is no use for them at all in the unity-specific implementation... do you know a way around this?

**Comment by joreg** [comment]
discussion not relevant to OP continues in chat.

**Comment by i-n-g-o** [comment]
just pushed changed for Vector3F32 widgets to the client. it is already live at:
https://rabbitcontrol.github.io/client/
could you try if this works for you?

**Comment by lukasIO** [comment]
@i-n-g-o nice! thanks for giving it a try so quickly. Can confirm that the widget/controls appear now :)
