### ISSUE TITLE
IntParam causing error

### ISSUE THREAD

**Issue by seltzdesign** [rabbitControl/rcp-ts-client#23]
I am still getting an error when trying to add an IntParam (see image). This is happening in the vvvv gamma help patch.

<img width="1460" alt="image" src="https://github.com/rabbitControl/rcp-ts-client/assets/6575829/50073a6f-db2a-4cb9-b706-1a09173a8e02">

In the sample patch the error did not appear after about the 5th or so reload. In our own implementation, we are always getting the error in the browser console.

Thanks for investigating!

**Comment by i-n-g-o** [comment]
I just tried with the current stable version of vvvv-gamma 5.2 and could not reproduce this behavior. Please make sure to install / update your nuget: `nuget install VL.IO.RCP -pre`
